model: FDSA

# Dataset & fields
dataset: mind_data_recbole_small
data_path: ./MIND/
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, title, categories]


# Text field
TEXT_FIELD: title
selected_features: ['categories']
embedding_size: 64

# Training settings
epochs: 50
train_batch_size: 512
eval_batch_size: 256
learning_rate: 0.001
stopping_step: 10
loss_type: CE
train_neg_sample_args: ~

# Evaluation
metrics: [Recall, NDCG, MRR]
topk: [10]
valid_metric: NDCG@10
eval_args:
  group_by: user
  order: TO
  mode: full

# Others
checkpoint_dir: ./saved_baselines_MIND/
show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3'
use_gpu: True