# ===================== Basic Info ===================== #
model: FDSA
dataset: finetune_music
data_path: ./MIND/mind_data_recbole_large

# ===================== Data Format =================
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, title, categories]

TEXT_FIELD: title
selected_features: ['categories']
embedding_size: 64

# ===================== Filtering ===================== #
min_user_inter_num: 1
min_item_inter_num: 1
filter_inter_by_user_or_item: False

# ===================== Dataset Splitting ===================== #
# Remove benchmark_filename; use RecBole's internal splitter
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}  # Random Split: train/valid/test
    group_by: user
    order: TO
    mode: full

# ===================== Training ===================== #
epochs: 20
train_batch_size: 512
eval_batch_size: 256
learning_rate: 5e-4
stopping_step: 5
loss_type: CE
train_neg_sample_args: ~

# ===================== Evaluation ===================== #
metrics: [Recall, NDCG, MRR]
topk: [10]
valid_metric: NDCG@10



# ===================== Checkpoint ===================== #
checkpoint_dir: ./saved_baselines_MIND/
pretrained_model_path: ./saved_baselines_MIND/FDSA-Jun-18-2025_12-09-56.pth


# ===================== Miscellaneous ===================== #
show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3'
use_gpu: True

