# ===================== Basic Info ===================== #
model: SASRec
dataset: mind_data_recbole_small
data_path: ./MIND/

# ===================== Data Format ===================== #
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id, title, categories]

PAD_TOKEN: "[PAD]"

# ===================== Dataset Splitting ===================== #
eval_args:
    group_by: user # Group OOD validation data by user for evaluation
    order: TO      
    mode: full  

# ===================== Training ===================== #
epochs: 50
train_batch_size: 1024
eval_batch_size: 512
learning_rate: 0.001
stopping_step: 10
loss_type: CE
train_neg_sample_args: ~

# ===================== Evaluation ===================== #
metrics: [Recall, NDCG, MRR]
topk: [10]
valid_metric: NDCG@10

# ===================== Checkpoint ===================== #
checkpoint_dir: ./saved_baselines_MIND/
#pretrained_model_path: ./saved_baselines/SASRec-May-21-2025_01-41-00.pth/SASRec-Jun-06-2025_10-12-44.pth

# ===================== Miscellaneous ===================== #
show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3'
use_gpu: True

