model: FDSA
dataset: Scientific
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, title, categories, brand]
data_path: ./recbole_data/

TEXT_FIELD: title
embedding_size: 64

# Finetune from saved checkpoint
checkpoint_dir: ./saved_baselines/FDSA-Scientific/
load_best_model: True

epochs: 20
train_batch_size: 512
eval_batch_size: 256
learning_rate: 5e-4
stopping_step: 5
loss_type: CE
train_neg_sample_args: ~

metrics: [Recall, NDCG, MRR]
topk: [10]
valid_metric: NDCG@10
eval_args:
  group_by: user
  order: TO
  mode: full

show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3'
use_gpu: True
