# ===================== Basic Info ===================== #
model: SASRec
dataset: finetune_scientific
item_file: finetune_scientific.item
data_path: ./recbole_data/

# ===================== Data Format ===================== #
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id, title, categories, brand]  # optional — use only if available

PAD_TOKEN: "[PAD]"

# ===================== Filtering ===================== #
min_user_inter_num: 1
min_item_inter_num: 1
filter_inter_by_user_or_item: False

# ===================== Dataset Splitting ===================== #
# Remove benchmark_filename; use RecBole's internal splitter
eval_args:
    split: {'RS': [0.8, 0.1, 0.1]}  # Random Split: train/valid/test
    group_by: user
    order: TO
    mode: full

# ===================== Training ===================== #
epochs: 20
train_batch_size: 512
eval_batch_size: 512
learning_rate: 0.0001
stopping_step: 5
loss_type: CE
train_neg_sample_args: ~

# ===================== Evaluation ===================== #
metrics: [Recall, NDCG, MRR]
topk: [10]
valid_metric: NDCG@10

# ===================== Checkpoint ===================== #
checkpoint_dir: ./saved_baselines/
pretrained_model_path: ./saved_baselines/SASRec-May-21-2025_01-41-00.pth/SASRec-Jun-06-2025_10-12-44.pth

# ===================== Miscellaneous ===================== #
show_progress: True
seed: 2025
reproducibility: True
gpu_id: '0,1,2,3'
use_gpu: True
